name       : openxcom
version    : 1.0
release    : 5
source     :
    - git|https://github.com/SupSuper/OpenXcom : a6d2d32495d9a2efa5b3460a284b7be33629129d
license    : GPL-3.0
component  : games.strategy
summary    : OpenXcom is an open-source clone of the popular UFO - Enemy Unknown videogame
description: |
    OpenXcom is an open-source clone of the popular UFO - Enemy Unknown videogame
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(sdl)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(yaml-cpp)
    - pkgconfig(x11)
    - libboost-devel
    - xmlto
setup      : |
    sed -i "s|(abs(|(std::abs(|g" src/Battlescape/ProjectileFlyBState.cpp
    sed -i "s| abs(| std::abs(|g" src/Geoscape/Globe.cpp
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 $pkgfiles/openxcom.desktop $installdir/usr/share/applications/openxcom.desktop
