name       : openxcom
version    : 1.0
release    : 1
source     :
    - https://github.com/SupSuper/OpenXcom/archive/v1.0.tar.gz : 45acb280010a01d60506b1c5f2951ae501c012cc6161aac470bd15c1e6981246
license    : GPL-3.0
component  : games.strategy
summary    : OpenXcom is an open-source clone of the popular UFO - Enemy Unknown videogame
description: |
    OpenXcom is an open-source clone of the popular UFO - Enemy Unknown videogame
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(sdl)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - xmlto
setup      : |
    sed -i "s|(abs(|(std::abs(|g" src/Battlescape/ProjectileFlyBState.cpp
    sed -i "s| abs(| std::abs(|g" src/Geoscape/Globe.cpp
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 $pkgfiles/openxcom.desktop $installdir/usr/share/applications/openxcom.desktop